version: "3"

services:

  postgres:
    image: "postgres:13.4-alpine"
    container_name: "db"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "35432:5432"


  main:
    container_name: "main"
    image: main:latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres

  user-service:
    container_name: "user-service"
    image: user-service:latest
    ports:
      - "9092:9092"
    depends_on:
      - postgres

  document-service:
    container_name: "document-service"
    image: document-service:latest
    ports:
      - "9093:9093"
    depends_on:
      - postgres

