version: "3"
services:

  localstack:
    container_name: "LocalStack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES:s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock


  postgres:
    image: "postgres:13.4-alpine"
    container_name: "localhost"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "35432:5432"
    volumes:
      - "./dev-env/postgres/init.sql:/docker-entrypoint-initdb.d/1-init.sql"


  main:
    container_name: "main"
    image: main:latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres


  user-service:
    container_name: "user-service"
    image: user-service:latest
    ports:
      - "9092:9092"
    depends_on:
      - postgres
