server:
  port: 9093

spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/documents
  jpa:
    database: POSTGRESQL
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  client:
    config:
      domain:
        connectTimeout: 5000
        readTimeout: 3000
