server:
  port: 9090

spring:
  datasource:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

jwtSecret: "SECRET"

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  client:
    config:
      domain:
        connectTimeout: 5000
        readTimeout: 3000

services:
  user:
    url: 'http://localhost:9092'